  version: '3'

  tasks:
    build-server:
      desc: Build the server
      cmds:
        - docker build -t wow-server:latest -f Dockerfile.server .

    build-client:
      desc: Build the client
      cmds:
        - docker build -t wow-client:latest -f Dockerfile.client .

    run-server:
      desc: Run the server
      cmds:
        - docker run -d --name wow-server --network wow-network -p 12345:12345 wow-server:latest

    run-client:
      desc: Run the client
      cmds:
        -  docker run --network wow-network wow-client:latest

    build-all:
      desc: Build both server and client
      cmds:
        - task: build-server
        - task: build-client

    run-all:
      desc: Run both server and client
      cmds:
        - task: run-server
        - task: run-client

    setup-network:
      desc: Create a Docker network
      cmds:
        -  docker network create wow-network

    cleanup:
      desc: Remove Docker images and network
      cmds:
        - docker rmi -f wow-server:latest wow-client:latest wow-server wow-client || true
        - docker stop wow-server
        - docker rm wow-server
        - docker network rm wow-network
